# Generated by Django 4.0.5 on 2022-06-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default=None, max_length=100)),
                ('deskripsi', models.TextField()),
                ('harga', models.PositiveIntegerField(default=None)),
                ('gambar', models.CharField(max_length=500)),
                ('timestamp', models.CharField(max_length=64)),
            ],
        ),
    ]
